### PR TITLE
Handle videos which are already in playlist

### PR DESCRIPTION
**Pull request by thomasgassmann**
Adds a switch to the command line, to skip videos, which already exist in the playlist.

### CODE REVIEW

**Comment by RobbieClarken** [comment]
Hi @ThomasGassmann, thanks for the contribution!

I'm happy to include this feature but it doesn't seem to be working for me. I've tried the following:
1. Create a new playlist
2. Populate it with `channel_to_playlist`
3. Delete the `*-added-videos` file
4. Run `channel_to_playlist` with `--skip_existing True`

I find that the videos are just added a second time to the playlist. Could there be some setting you have turned on for your playlist to reject duplicates?

**Comment by thomasgassmann** [comment]
Hi @RobbieClarken,
I've just tried to reproduce your error. And according to my investigation, it seems as if YouTube treats the watch later playlist (ID being "WL") differently than all the other playlists. While it is adding the videos twice on a regular playlist, it is throwing the 409 conflict error in the WL playlist. 
Can you reproduce this behaviour in your WL playlist?

Right now I am even getting the following response from my WL playlist, which seems kind of weird:
`<HttpError 500 when requesting https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&alt=json returned "Backend Error">`
I will try to investigate that a little further this weekend and will follow up on this PR.

**Comment by RobbieClarken** [comment]
> Can you reproduce this behaviour in your WL playlist?

Aha! I do get 409 when adding to my Watch Later playlist and your `--skip-existing` flag then works as expected.

If we are to add a `--skip-existing` flag it should work for both Watch Later and regular playlists. So the options are:
1. Remove the `--skip-existing` option but retain the exception handling of 409's. Perhaps just log the exception as it contains the helpful explanation "Video already in playlist.".
2. Keep the `--skip-existing` option and query youtube for which videos are already in the playlist and skip adding them for all types of playlists. If we go down this route I think the default for `--skip-existing` should be `True`.

I'm happy with either approach. What do you think?

**Comment by thomasgassmann** [comment]
I've decided to implement approach 2, because it avoids a 409 response and seems like a cleaner solution to me. 
See 2dcb31a for these changes.

**Comment by RobbieClarken** [comment]
Thanks @ThomasGassmann! I made a few changes before merging (hope you don't mind):

- I renamed the `--skip_existing` to `--allow-duplicates` and used the [`action="store_true"`](https://github.com/RobbieClarken/youtube-channel-to-playlist/blob/7cecece40b1d94927dc21f5d8257c13a9c13a966/channel_to_playlist.py#L109) argument so you don't need to specify a value for this option (leaving it off defaults to `False`)
- I had to re-add the exception handling for watch later playlists because [it doesn't seem to be possible to query youtube for videos on this playlist](https://stackoverflow.com/a/47117301/568774)

**Pull request closed without merging**
